version: "3.3"
   
services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - ./static:/var/www/static
      - ./media:/var/www/media
  web:
    build: .
    command: gunicorn project.wsgi:application --reload --bind 0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - ./static:/code/static
      - ./media:/code/media
